openapi: 3.0.0
info:
  title: '1.0'
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/wallum-systems/simple-accounting-system-api/blob/master/LICENSE'
servers:
  - url: /v1.0
paths:
  /accounts:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
              examples: {}
      operationId: get-account
    parameters: []
  '/accounts/{id}/records':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: The id of the account to query
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountWithRecords'
      operationId: get-account-id-records
      parameters: []
      description: ''
  /ping:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-ping
  /records:
    get:
      summary: Get all records
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Record'
              examples: {}
      operationId: get-record
    post:
      summary: ''
      operationId: post-record
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRecord'
        description: ''
    parameters: []
  '/records/{id}/receipts':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: The id of the record
    post:
      summary: ''
      operationId: post-records-id-receipt
      responses:
        '201':
          description: Created - The receipt was successfully added to the record.
      description: Add a receipt to the booking
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                receipt:
                  type: string
                  format: binary
                  description: The receipt of the record
              required:
                - name
                - receipt
            encoding:
              receipt:
                contentType: application/pdf
            examples: {}
  '/records/{id}/revert':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: The id of the record to be reverted
    post:
      summary: Revert record
      tags: []
      responses:
        '202':
          description: 'Accepted - Returns the record associated with the given id, which is now reverted'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
        '404':
          description: Not Found - No record was found for the given id
        '405':
          description: Method Not Allowed - This method can not be called on reverting records and tax records.
          headers: {}
      operationId: post-revert-record
      description: Allows to revert a record. It can not be called on reverting records.
  /recurringRecords:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-recurringRecords
  '/recurringRecords/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-recurringRecords-id
    delete:
      summary: ''
      operationId: delete-recurringRecords-id
      responses:
        '200':
          description: OK
  /taxes:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tax'
      operationId: get-tax
    parameters: []
components:
  schemas:
    Account:
      title: Account
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    AccountWithRecords:
      title: AccountWithRecords
      allOf:
        - $ref: '#/components/schemas/Account'
        - type: object
          properties:
            incomingRecords:
              type: array
              items:
                $ref: '#/components/schemas/Record'
        - type: object
          properties:
            outgoingRecords:
              type: array
              items:
                $ref: '#/components/schemas/Record'
      x-examples: {}
    BaseRecord:
      title: BaseRecord
      allOf:
        - $ref: '#/components/schemas/NoDateBaseRecord'
        - type: object
          properties:
            bookingDate:
              type: string
              format: date
          required:
            - bookingDate
    NewRecord:
      title: NewRecord
      allOf:
        - $ref: '#/components/schemas/BaseRecord'
        - type: object
          properties:
            taxRecord:
              $ref: '#/components/schemas/NoDateBaseRecord'
    NoDateBaseRecord:
      title: BaseRecord
      type: object
      properties:
        id:
          type: integer
          description: The id of the record
          readOnly: true
        description:
          type: string
          description: The description for the record
        amount:
          type: number
          description: The amount to be transfered
        fromAccountId:
          type: integer
        toAccountId:
          type: integer
        creationTime:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - description
        - amount
        - fromAccountId
        - toAccountId
        - creationTime
    Record:
      title: Record
      allOf:
        - $ref: '#/components/schemas/BaseRecord'
        - type: object
          properties:
            taxRecord:
              type: integer
            taxedRecord:
              type: integer
            revertingRecord:
              type: integer
            revertedRecord:
              type: integer
      description: ''
      x-examples: {}
    Tax:
      title: Tax
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        tax:
          type: number
          description: Tax amount as number between 0 an 1
          minimum: 0
          maximum: 1
      required:
        - id
        - name
        - tax
    NewRecurringRecord:
      title: NewRecurringRecord
      allOf:
        - $ref: '#/components/schemas/NewRecord'
        - $ref: '#/components/schemas/RecurrenceInterval'
    RecurringRecord:
      allOf:
        - $ref: '#/components/schemas/BaseRecord'
        - $ref: '#/components/schemas/RecurrenceInterval'
    RecurrenceInterval:
      title: RecurrenceInterval
      type: object
      properties:
        value:
          type: string
          enum:
            - DAYLY
            - MONTHLY
            - QUARTERLY
            - YEARLY
      required:
        - value
  securitySchemes: {}
